//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ATSQuadroStrategyBase.GUI;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
//using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace ATSQuadroStrategyBase.GUI {
    
    
    /// <summary>
    /// UserControlNinjaBuddy
    /// </summary>
    public partial class UserControlNinjaBuddy : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 10 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal ATSQuadroStrategyBase.GUI.UserControlNinjaBuddy UCNinjaBuddy;
        
        #line default
        #line hidden
        
        
        #line 595 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdMain;
        
        #line default
        #line hidden
        
        
        #line 597 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RowDefinition RowHeader;
        
        #line default
        #line hidden
        
        
        #line 598 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RowDefinition RowAskBid;
        
        #line default
        #line hidden
        
        
        #line 599 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RowDefinition RowAlgoSetup;
        
        #line default
        #line hidden
        
        
        #line 600 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RowDefinition RowButtonsEntry;
        
        #line default
        #line hidden
        
        
        #line 601 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RowDefinition RowBoxBreakout;
        
        #line default
        #line hidden
        
        
        #line 602 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RowDefinition RowPostitionManagment;
        
        #line default
        #line hidden
        
        
        #line 603 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RowDefinition RowFooter;
        
        #line default
        #line hidden
        
        
        #line 605 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdHeader;
        
        #line default
        #line hidden
        
        
        #line 612 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBoxInstrumentFullName;
        
        #line default
        #line hidden
        
        
        #line 613 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBoxHeader;
        
        #line default
        #line hidden
        
        
        #line 614 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBoxHeaderPL;
        
        #line default
        #line hidden
        
        
        #line 623 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBoxSystemMode;
        
        #line default
        #line hidden
        
        
        #line 624 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBoxSystemStatus;
        
        #line default
        #line hidden
        
        
        #line 628 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdBidAsk;
        
        #line default
        #line hidden
        
        
        #line 643 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdAlgoSetup;
        
        #line default
        #line hidden
        
        
        #line 653 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox cbAutomatedTrading;
        
        #line default
        #line hidden
        
        
        #line 654 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox cbAutoLong;
        
        #line default
        #line hidden
        
        
        #line 655 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox cbAutoShort;
        
        #line default
        #line hidden
        
        
        #line 657 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdButtonsEntry;
        
        #line default
        #line hidden
        
        
        #line 667 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnBuy;
        
        #line default
        #line hidden
        
        
        #line 668 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSell;
        
        #line default
        #line hidden
        
        
        #line 669 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnOCOBreakout;
        
        #line default
        #line hidden
        
        
        #line 682 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox cbUpper;
        
        #line default
        #line hidden
        
        
        #line 683 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox cbLower;
        
        #line default
        #line hidden
        
        
        #line 686 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnBoxClear;
        
        #line default
        #line hidden
        
        
        #line 702 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnClosePositions;
        
        #line default
        #line hidden
        
        
        #line 703 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnTrail50;
        
        #line default
        #line hidden
        
        
        #line 704 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnTrailHiLo;
        
        #line default
        #line hidden
        
        
        #line 705 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnBreakEven;
        
        #line default
        #line hidden
        
        
        #line 706 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSetTrail;
        
        #line default
        #line hidden
        
        
        #line 707 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnTrail1;
        
        #line default
        #line hidden
        
        
        #line 708 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnTrail2;
        
        #line default
        #line hidden
        
        
        #line 709 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnTrail3;
        
        #line default
        #line hidden
        
        
        #line 710 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnTrail4;
        
        #line default
        #line hidden
        
        
        #line 717 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox textPositionState;
        
        #line default
        #line hidden
        
        
        #line 718 "..\..\UserControlNinjaBuddy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox textUnrealizedPL;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/ATSQuadroStrategyBase.GUI;component/usercontrolninjabuddy.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\UserControlNinjaBuddy.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.UCNinjaBuddy = ((ATSQuadroStrategyBase.GUI.UserControlNinjaBuddy)(target));
            return;
            case 3:
            this.grdMain = ((System.Windows.Controls.Grid)(target));
            return;
            case 4:
            this.RowHeader = ((System.Windows.Controls.RowDefinition)(target));
            return;
            case 5:
            this.RowAskBid = ((System.Windows.Controls.RowDefinition)(target));
            return;
            case 6:
            this.RowAlgoSetup = ((System.Windows.Controls.RowDefinition)(target));
            return;
            case 7:
            this.RowButtonsEntry = ((System.Windows.Controls.RowDefinition)(target));
            return;
            case 8:
            this.RowBoxBreakout = ((System.Windows.Controls.RowDefinition)(target));
            return;
            case 9:
            this.RowPostitionManagment = ((System.Windows.Controls.RowDefinition)(target));
            return;
            case 10:
            this.RowFooter = ((System.Windows.Controls.RowDefinition)(target));
            return;
            case 11:
            this.grdHeader = ((System.Windows.Controls.Grid)(target));
            return;
            case 12:
            this.textBoxInstrumentFullName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.textBoxHeader = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 14:
            this.textBoxHeaderPL = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 15:
            this.textBoxSystemMode = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 16:
            this.textBoxSystemStatus = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 17:
            this.grdBidAsk = ((System.Windows.Controls.Grid)(target));
            return;
            case 18:
            this.grdAlgoSetup = ((System.Windows.Controls.Grid)(target));
            return;
            case 19:
            this.cbAutomatedTrading = ((System.Windows.Controls.CheckBox)(target));
            
            #line 653 "..\..\UserControlNinjaBuddy.xaml"
            this.cbAutomatedTrading.Checked += new System.Windows.RoutedEventHandler(this.cbAutomatedTrading_Checked);
            
            #line default
            #line hidden
            
            #line 653 "..\..\UserControlNinjaBuddy.xaml"
            this.cbAutomatedTrading.Unchecked += new System.Windows.RoutedEventHandler(this.cbAutomatedTrading_Unchecked);
            
            #line default
            #line hidden
            return;
            case 20:
            this.cbAutoLong = ((System.Windows.Controls.CheckBox)(target));
            
            #line 654 "..\..\UserControlNinjaBuddy.xaml"
            this.cbAutoLong.Checked += new System.Windows.RoutedEventHandler(this.cbAutoLong_Checked);
            
            #line default
            #line hidden
            
            #line 654 "..\..\UserControlNinjaBuddy.xaml"
            this.cbAutoLong.Unchecked += new System.Windows.RoutedEventHandler(this.cbAutoLong_Unchecked);
            
            #line default
            #line hidden
            return;
            case 21:
            this.cbAutoShort = ((System.Windows.Controls.CheckBox)(target));
            
            #line 655 "..\..\UserControlNinjaBuddy.xaml"
            this.cbAutoShort.Checked += new System.Windows.RoutedEventHandler(this.cbAutoShort_Checked);
            
            #line default
            #line hidden
            
            #line 655 "..\..\UserControlNinjaBuddy.xaml"
            this.cbAutoShort.Unchecked += new System.Windows.RoutedEventHandler(this.cbAutoShort_Unchecked);
            
            #line default
            #line hidden
            return;
            case 22:
            this.grdButtonsEntry = ((System.Windows.Controls.Grid)(target));
            return;
            case 23:
            this.btnBuy = ((System.Windows.Controls.Button)(target));
            
            #line 667 "..\..\UserControlNinjaBuddy.xaml"
            this.btnBuy.Click += new System.Windows.RoutedEventHandler(this.btnBuy_Click);
            
            #line default
            #line hidden
            return;
            case 24:
            this.btnSell = ((System.Windows.Controls.Button)(target));
            
            #line 668 "..\..\UserControlNinjaBuddy.xaml"
            this.btnSell.Click += new System.Windows.RoutedEventHandler(this.btnSell_Click);
            
            #line default
            #line hidden
            return;
            case 25:
            this.btnOCOBreakout = ((System.Windows.Controls.Button)(target));
            
            #line 669 "..\..\UserControlNinjaBuddy.xaml"
            this.btnOCOBreakout.Click += new System.Windows.RoutedEventHandler(this.btnOCOBreakout_Click);
            
            #line default
            #line hidden
            return;
            case 26:
            this.cbUpper = ((System.Windows.Controls.CheckBox)(target));
            
            #line 682 "..\..\UserControlNinjaBuddy.xaml"
            this.cbUpper.Checked += new System.Windows.RoutedEventHandler(this.cbUpper_Checked);
            
            #line default
            #line hidden
            return;
            case 27:
            this.cbLower = ((System.Windows.Controls.CheckBox)(target));
            
            #line 683 "..\..\UserControlNinjaBuddy.xaml"
            this.cbLower.Checked += new System.Windows.RoutedEventHandler(this.cbLower_Checked);
            
            #line default
            #line hidden
            return;
            case 28:
            this.btnBoxClear = ((System.Windows.Controls.Button)(target));
            
            #line 686 "..\..\UserControlNinjaBuddy.xaml"
            this.btnBoxClear.Click += new System.Windows.RoutedEventHandler(this.btnBoxClear_Click);
            
            #line default
            #line hidden
            return;
            case 29:
            this.btnClosePositions = ((System.Windows.Controls.Button)(target));
            
            #line 702 "..\..\UserControlNinjaBuddy.xaml"
            this.btnClosePositions.Click += new System.Windows.RoutedEventHandler(this.btnClosePositions_Click);
            
            #line default
            #line hidden
            return;
            case 30:
            this.btnTrail50 = ((System.Windows.Controls.Button)(target));
            
            #line 703 "..\..\UserControlNinjaBuddy.xaml"
            this.btnTrail50.Click += new System.Windows.RoutedEventHandler(this.btnTrail50_Click);
            
            #line default
            #line hidden
            return;
            case 31:
            this.btnTrailHiLo = ((System.Windows.Controls.Button)(target));
            
            #line 704 "..\..\UserControlNinjaBuddy.xaml"
            this.btnTrailHiLo.Click += new System.Windows.RoutedEventHandler(this.btnTrailHiLo_Click);
            
            #line default
            #line hidden
            return;
            case 32:
            this.btnBreakEven = ((System.Windows.Controls.Button)(target));
            
            #line 705 "..\..\UserControlNinjaBuddy.xaml"
            this.btnBreakEven.Click += new System.Windows.RoutedEventHandler(this.btnBreakEven_Click);
            
            #line default
            #line hidden
            return;
            case 33:
            this.btnSetTrail = ((System.Windows.Controls.Button)(target));
            
            #line 706 "..\..\UserControlNinjaBuddy.xaml"
            this.btnSetTrail.Click += new System.Windows.RoutedEventHandler(this.btnSetTrail_Click);
            
            #line default
            #line hidden
            return;
            case 34:
            this.btnTrail1 = ((System.Windows.Controls.Button)(target));
            
            #line 707 "..\..\UserControlNinjaBuddy.xaml"
            this.btnTrail1.Click += new System.Windows.RoutedEventHandler(this.btnTrail1_Click);
            
            #line default
            #line hidden
            return;
            case 35:
            this.btnTrail2 = ((System.Windows.Controls.Button)(target));
            
            #line 708 "..\..\UserControlNinjaBuddy.xaml"
            this.btnTrail2.Click += new System.Windows.RoutedEventHandler(this.btnTrail2_Click);
            
            #line default
            #line hidden
            return;
            case 36:
            this.btnTrail3 = ((System.Windows.Controls.Button)(target));
            
            #line 709 "..\..\UserControlNinjaBuddy.xaml"
            this.btnTrail3.Click += new System.Windows.RoutedEventHandler(this.btnTrail3_Click);
            
            #line default
            #line hidden
            return;
            case 37:
            this.btnTrail4 = ((System.Windows.Controls.Button)(target));
            
            #line 710 "..\..\UserControlNinjaBuddy.xaml"
            this.btnTrail4.Click += new System.Windows.RoutedEventHandler(this.btnTrail4_Click);
            
            #line default
            #line hidden
            return;
            case 38:
            this.textPositionState = ((System.Windows.Controls.TextBox)(target));
            
            #line 717 "..\..\UserControlNinjaBuddy.xaml"
            this.textPositionState.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.textPositionState_TextChanged);
            
            #line default
            #line hidden
            return;
            case 39:
            this.textUnrealizedPL = ((System.Windows.Controls.TextBox)(target));
            
            #line 718 "..\..\UserControlNinjaBuddy.xaml"
            this.textUnrealizedPL.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.textUnrealizedPL_TextChanged);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 2:
            
            #line 344 "..\..\UserControlNinjaBuddy.xaml"
            ((System.Windows.Controls.Primitives.ToggleButton)(target)).Checked += new System.Windows.RoutedEventHandler(this.HeaderSite_Checked);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

