//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ATSQuadroStrategyBase.GUI;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.WpfPropertyGrid;
using System.Windows.Controls.WpfPropertyGrid.Controls;
using System.Windows.Controls.WpfPropertyGrid.Design;
using System.Windows.Data;
using System.Windows.Documents;
//using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace ATSQuadroStrategyBase.GUI {
    
    
    /// <summary>
    /// UserControlEasyConfig
    /// </summary>
    public partial class UserControlEasyConfig : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 136 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdMain;
        
        #line default
        #line hidden
        
        
        #line 141 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RowDefinition RowTemplateHeader;
        
        #line default
        #line hidden
        
        
        #line 142 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RowDefinition RowTemplateControls;
        
        #line default
        #line hidden
        
        
        #line 143 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RowDefinition RowPropertyGridControls;
        
        #line default
        #line hidden
        
        
        #line 145 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdTemplateInfo;
        
        #line default
        #line hidden
        
        
        #line 155 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblSettingID;
        
        #line default
        #line hidden
        
        
        #line 158 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdButtonsEntry;
        
        #line default
        #line hidden
        
        
        #line 175 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnLoad;
        
        #line default
        #line hidden
        
        
        #line 176 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnRefresh;
        
        #line default
        #line hidden
        
        
        #line 177 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnSave;
        
        #line default
        #line hidden
        
        
        #line 178 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnSaveAs;
        
        #line default
        #line hidden
        
        
        #line 179 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnOk;
        
        #line default
        #line hidden
        
        
        #line 180 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnApply;
        
        #line default
        #line hidden
        
        
        #line 181 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnCancel;
        
        #line default
        #line hidden
        
        
        #line 182 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnClose;
        
        #line default
        #line hidden
        
        
        #line 183 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnRestart;
        
        #line default
        #line hidden
        
        
        #line 185 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl TabControlMain;
        
        #line default
        #line hidden
        
        
        #line 194 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabSetup;
        
        #line default
        #line hidden
        
        
        #line 195 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridSetup;
        
        #line default
        #line hidden
        
        
        #line 196 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer GirdSetup;
        
        #line default
        #line hidden
        
        
        #line 197 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.WpfPropertyGrid.PropertyGrid PropertyGrid1;
        
        #line default
        #line hidden
        
        
        #line 202 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridEntryFilters;
        
        #line default
        #line hidden
        
        
        #line 203 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer ScrollViewerFilters;
        
        #line default
        #line hidden
        
        
        #line 204 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.WpfPropertyGrid.PropertyGrid PropertyGrid2;
        
        #line default
        #line hidden
        
        
        #line 209 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridExits;
        
        #line default
        #line hidden
        
        
        #line 210 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer ScrollViewerExits;
        
        #line default
        #line hidden
        
        
        #line 211 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.WpfPropertyGrid.PropertyGrid PropertyGrid3;
        
        #line default
        #line hidden
        
        
        #line 216 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridHTF;
        
        #line default
        #line hidden
        
        
        #line 217 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer ScrollViewerHTF;
        
        #line default
        #line hidden
        
        
        #line 218 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.WpfPropertyGrid.PropertyGrid PropertyGrid4;
        
        #line default
        #line hidden
        
        
        #line 223 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridTradeMan;
        
        #line default
        #line hidden
        
        
        #line 224 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer ScrollViewerTradeMan;
        
        #line default
        #line hidden
        
        
        #line 225 "..\..\UserControlEasyConfig.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.WpfPropertyGrid.PropertyGrid PropertyGrid5;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/ATSQuadroStrategyBase.GUI;component/usercontroleasyconfig.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\UserControlEasyConfig.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.grdMain = ((System.Windows.Controls.Grid)(target));
            return;
            case 2:
            this.RowTemplateHeader = ((System.Windows.Controls.RowDefinition)(target));
            return;
            case 3:
            this.RowTemplateControls = ((System.Windows.Controls.RowDefinition)(target));
            return;
            case 4:
            this.RowPropertyGridControls = ((System.Windows.Controls.RowDefinition)(target));
            return;
            case 5:
            this.grdTemplateInfo = ((System.Windows.Controls.Grid)(target));
            return;
            case 6:
            this.lblSettingID = ((System.Windows.Controls.Label)(target));
            return;
            case 7:
            this.grdButtonsEntry = ((System.Windows.Controls.Grid)(target));
            return;
            case 8:
            this.BtnLoad = ((System.Windows.Controls.Button)(target));
            
            #line 175 "..\..\UserControlEasyConfig.xaml"
            this.BtnLoad.Click += new System.Windows.RoutedEventHandler(this.BtnLoad_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.BtnRefresh = ((System.Windows.Controls.Button)(target));
            
            #line 176 "..\..\UserControlEasyConfig.xaml"
            this.BtnRefresh.Click += new System.Windows.RoutedEventHandler(this.BtnRefresh_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            this.BtnSave = ((System.Windows.Controls.Button)(target));
            
            #line 177 "..\..\UserControlEasyConfig.xaml"
            this.BtnSave.Click += new System.Windows.RoutedEventHandler(this.BtnSave_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            this.BtnSaveAs = ((System.Windows.Controls.Button)(target));
            
            #line 178 "..\..\UserControlEasyConfig.xaml"
            this.BtnSaveAs.Click += new System.Windows.RoutedEventHandler(this.BtnSaveAs_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.BtnOk = ((System.Windows.Controls.Button)(target));
            
            #line 179 "..\..\UserControlEasyConfig.xaml"
            this.BtnOk.Click += new System.Windows.RoutedEventHandler(this.BtnOk_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.BtnApply = ((System.Windows.Controls.Button)(target));
            
            #line 180 "..\..\UserControlEasyConfig.xaml"
            this.BtnApply.Click += new System.Windows.RoutedEventHandler(this.BtnApply_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            this.BtnCancel = ((System.Windows.Controls.Button)(target));
            
            #line 181 "..\..\UserControlEasyConfig.xaml"
            this.BtnCancel.Click += new System.Windows.RoutedEventHandler(this.BtnCancel_Click);
            
            #line default
            #line hidden
            return;
            case 15:
            this.BtnClose = ((System.Windows.Controls.Button)(target));
            return;
            case 16:
            this.BtnRestart = ((System.Windows.Controls.Button)(target));
            
            #line 183 "..\..\UserControlEasyConfig.xaml"
            this.BtnRestart.Click += new System.Windows.RoutedEventHandler(this.BtnRestart_Click);
            
            #line default
            #line hidden
            return;
            case 17:
            this.TabControlMain = ((System.Windows.Controls.TabControl)(target));
            return;
            case 18:
            this.TabSetup = ((System.Windows.Controls.TabItem)(target));
            return;
            case 19:
            this.GridSetup = ((System.Windows.Controls.Grid)(target));
            return;
            case 20:
            this.GirdSetup = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 21:
            this.PropertyGrid1 = ((System.Windows.Controls.WpfPropertyGrid.PropertyGrid)(target));
            return;
            case 22:
            this.GridEntryFilters = ((System.Windows.Controls.Grid)(target));
            return;
            case 23:
            this.ScrollViewerFilters = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 24:
            this.PropertyGrid2 = ((System.Windows.Controls.WpfPropertyGrid.PropertyGrid)(target));
            return;
            case 25:
            this.GridExits = ((System.Windows.Controls.Grid)(target));
            return;
            case 26:
            this.ScrollViewerExits = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 27:
            this.PropertyGrid3 = ((System.Windows.Controls.WpfPropertyGrid.PropertyGrid)(target));
            return;
            case 28:
            this.GridHTF = ((System.Windows.Controls.Grid)(target));
            return;
            case 29:
            this.ScrollViewerHTF = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 30:
            this.PropertyGrid4 = ((System.Windows.Controls.WpfPropertyGrid.PropertyGrid)(target));
            return;
            case 31:
            this.GridTradeMan = ((System.Windows.Controls.Grid)(target));
            return;
            case 32:
            this.ScrollViewerTradeMan = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 33:
            this.PropertyGrid5 = ((System.Windows.Controls.WpfPropertyGrid.PropertyGrid)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

